### ISSUE TITLE
All Towers fail at startup

### ISSUE THREAD

**Issue by minimike96** [doombubbles/ultimate-crosspathing#104]
# Installation Error

### Mod Version
1.4.0

### Mod Helper Version
3.1.6

### Description
When launching game 23 Towers fail to crosspath. This happens with only Ultimate Crosspath and ModHelper installed/Enabled. I've uninstalled/reinstalled both ModHelper and Crosspath mods. MelonLoader is on 0.6.0

### Other Mods
None

### Logs
Example of error from Alchemist:

[18:55:00.517] [BloonsTD6_Mod_Helper] AlchemistLoader failed loading bytes
[18:55:00.520] [BloonsTD6_Mod_Helper] System.ArgumentException: Il2CppStructArray requires an Il2Cpp reference type, which Il2CppAssets.Scripts.Models.Map.AreaType isn't
   at Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1.AllocateArray(Int64 size) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Arrays/Il2CppStructArray.cs:line 60
   at Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1..ctor(T[] arr) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Arrays/Il2CppStructArray.cs:line 20
   at Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1.op_Implicit(T[] arr) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Arrays/Il2CppStructArray.cs:line 50
   at UltimateCrosspathing.Loaders.AlchemistLoader.Set_v_TowerModel_Fields(Int32 start, Int32 count) in /home/runner/work/ultimate-crosspathing/ultimate-crosspathing/UltimateCrosspathing/Loaders/AlchemistLoader.cs:line 223
   at UltimateCrosspathing.Loaders.AlchemistLoader.Load(Byte[] bytes) in /home/runner/work/ultimate-crosspathing/ultimate-crosspathing/UltimateCrosspathing/Loaders/AlchemistLoader.cs:line 1392
   at BTD_Mod_Helper.Api.ModByteLoader`1.OnBytesLoaded()
   at BTD_Mod_Helper.Api.ModByteLoader.LoadAllBytes()

All towers fail, full log also attached

[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/11174923/Latest.log)

**Comment by doombubbles** [comment]
Please update to [MelonLoader 0.6.1](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer

**Comment by minimike96** [comment]
> Please update to [MelonLoader 0.6.1](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1). Will also appear in the official MelonLoader installer

MelonLoader update fixed this, thank you!
