### ISSUE TITLE
Issue with loading MelonLoader

### ISSUE THREAD

**Issue by CrystalWolfYT** [doombubbles/ultimate-crosspathing#87]
I've come across this recently, but every time I open BTD6, I get an error saying there is "no support module loaded" I have no clue if it is referring to the Mod Helper That is currently installed, or if it's the crosspathing mod itself, but upon loading. the entire thing crashes.

The Crash being logged below:
04:43:22.758] ------------------------------
[04:43:22.860] MelonLoader v0.5.7 Open-Beta
[04:43:22.861] OS: Windows 10
[04:43:22.861] Hash Code: 49999848531024954985654485098975250521005157544948501005510199495356
[04:43:22.862] ------------------------------
[04:43:22.863] Game Type: Il2Cpp
[04:43:22.864] Game Arch: x64
[04:43:22.867] ------------------------------
[04:43:22.872] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[04:43:22.897] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[04:43:22.910] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[04:43:22.931] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe

[04:43:24.151] ------------------------------
[04:43:24.153] Game Name: BloonsTD6
[04:43:24.172] Game Developer: Ninja Kiwi
[04:43:24.181] Unity Version: 2021.3.12f1
[04:43:24.184] Game Version: 34.3
[04:43:24.187] ------------------------------

[04:43:24.532] Preferences Loaded!
[04:43:24.539] [Il2CppUnityTls] Patching mono_unity_get_unitytls_interface...
[04:43:24.540] [Il2CppUnityTls] Patching il2cpp_unity_install_unitytls_interface...
[04:43:24.899] [Il2CppUnityTls] Calling Il2CppInstallUnityTlsInterface...

[04:43:24.926] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Plugins'...
[04:43:24.927] 0 Plugins loaded.

[04:43:25.604] [MelonStartScreen] Initializing...
[04:43:25.646] [MelonStartScreen] Using Start Screen Theme: "Default"
[04:43:26.797] Loading Il2CppAssemblyGenerator...
[04:43:26.843] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[04:43:27.527] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[04:43:27.529] [Il2CppAssemblyGenerator] RemoteAPI.UnhollowerVersion = null
[04:43:27.530] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[04:43:27.531] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[04:43:27.532] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[04:43:27.534] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.8
[04:43:27.535] [Il2CppAssemblyGenerator] Using Il2CppAssemblyUnhollower Version = 0.4.18.0
[04:43:27.537] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.12
[04:43:27.539] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[04:43:27.540] [Il2CppAssemblyGenerator] Downloading Cpp2IL...
[04:43:27.541] [Il2CppAssemblyGenerator] Downloading https://github.com/SamboyCoding/Cpp2IL/releases/download/2022.1.0-pre-release.8/Cpp2IL-2022.1.0-pre-release.8-Windows-Netframework472.zip to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.8.zip
[04:43:28.270] [Il2CppAssemblyGenerator] Processing Cpp2IL...
[04:43:28.274] [Il2CppAssemblyGenerator] Creating Directory C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[04:43:28.276] [Il2CppAssemblyGenerator] Extracting C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.8.zip to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[04:43:28.630] [Il2CppAssemblyGenerator] Downloading Il2CppAssemblyUnhollower...
[04:43:28.631] [Il2CppAssemblyGenerator] Downloading https://github.com/knah/Il2CppAssemblyUnhollower/releases/download/v0.4.18.0/Il2CppAssemblyUnhollower.0.4.18.0.zip to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower_0.4.18.0.zip
[04:43:28.913] [Il2CppAssemblyGenerator] Processing Il2CppAssemblyUnhollower...
[04:43:28.915] [Il2CppAssemblyGenerator] Creating Directory C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower
[04:43:28.916] [Il2CppAssemblyGenerator] Extracting C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower_0.4.18.0.zip to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower
[04:43:28.993] [Il2CppAssemblyGenerator] Downloading UnityDependencies...
[04:43:28.995] [Il2CppAssemblyGenerator] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2021.3.12.zip to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2021.3.12.zip
[04:43:29.843] [Il2CppAssemblyGenerator] Processing UnityDependencies...
[04:43:29.844] [Il2CppAssemblyGenerator] Creating Directory C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[04:43:29.846] [Il2CppAssemblyGenerator] Extracting C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2021.3.12.zip to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[04:43:30.941] [Il2CppAssemblyGenerator] Checking GameAssembly...
[04:43:31.479] [Il2CppAssemblyGenerator] Assembly Generation Needed!
[04:43:31.483] [Il2CppAssemblyGenerator] Executing Cpp2IL...
[04:43:31.486] [Il2CppAssemblyGenerator] "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Cpp2IL.exe" --game-path "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6" --exe-name "BloonsTD6" --use-processor attributeinjector --output-as dummydll
[04:43:31.593] [Il2CppAssemblyGenerator] ===Cpp2IL by Samboy063===
[04:43:31.596] [Il2CppAssemblyGenerator] A Tool to Reverse Unity's "il2cpp" Build Process.
[04:43:31.597] [Il2CppAssemblyGenerator] Version 2022.1.0-pre-release.8
[04:43:31.598] [Il2CppAssemblyGenerator] 
[04:43:31.605] [Il2CppAssemblyGenerator] [Warn] [Program] NO_COLOR set, disabling ANSI color codes as you requested.
[04:43:31.606] [Il2CppAssemblyGenerator] [Info] [Program] Running on Win32NT
[04:43:31.759] [Il2CppAssemblyGenerator] [Info] [Plugins] Loading plugins from C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Plugins...
[04:43:31.786] [Il2CppAssemblyGenerator] [Info] [Plugins] Using Plugin: Cpp2IL Built-In
[04:43:31.798] [Il2CppAssemblyGenerator] [Info] [Program] Determined game's unity version to be 2021.3.12a0
[04:43:31.873] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Metadata...
[04:43:31.875] [Il2CppAssemblyGenerator] [Info] [Library] 	Using actual IL2CPP Metadata version 29
[04:43:32.101] [Il2CppAssemblyGenerator] [Info] [Library] Initialized Metadata in 227ms
[04:43:32.103] [Il2CppAssemblyGenerator] [Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[04:43:32.104] [Il2CppAssemblyGenerator] [Info] [Library] Searching Binary for Required Data...
[04:43:32.423] [Il2CppAssemblyGenerator] [Info] [Library] Got Binary codereg: 0x182613640, metareg: 0x182A7A750 in 321ms.
[04:43:32.424] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Binary...
[04:43:32.526] [Il2CppAssemblyGenerator] [Info] [Library] Initialized Binary in 102ms
[04:43:32.629] [Il2CppAssemblyGenerator] [Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 115059 OK (104ms)
[04:43:32.643] [Il2CppAssemblyGenerator] [Info] [Program] Creating application model...
[04:43:33.373] [Il2CppAssemblyGenerator] [Warn] [Program] StartOfNextFunc returned va 0xECE7002C74FC0, raw address 0x0, for raw address 0x251EAC0. It should be more than raw address. Falling back to manual, slow, decompiler-based approach.
[04:43:33.444] [Il2CppAssemblyGenerator] [Warn] [Program] StartOfNextFunc returned va 0xECE7002C74FC0, raw address 0x0, for raw address 0x251EAC0. It should be more than raw address. Falling back to manual, slow, decompiler-based approach.
[04:43:33.657] [Il2CppAssemblyGenerator] [Info] [Program] Application model created in 1012.8165ms
[04:43:33.658] [Il2CppAssemblyGenerator] [Info] [Program] Pre-processing processing layers...
[04:43:33.659] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector...
[04:43:33.660] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector finished in 0ms
[04:43:33.660] [Il2CppAssemblyGenerator] [Info] [Program] Invoking processing layers...
[04:43:33.661] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector...
[04:43:34.918] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector finished in 1260.585ms
[04:43:34.921] [Il2CppAssemblyGenerator] [Info] [Program] Outputting as Stub ("Dummy") DLL Files to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\cpp2il_out...
[04:43:40.900] [Il2CppAssemblyGenerator] [ERROR] 
[04:43:40.941] [Il2CppAssemblyGenerator] [ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Object elements in a custom attribute signature should be either 'null' or an instance of BoxedArgument.
[04:43:40.942] [Il2CppAssemblyGenerator] [ERROR]    --- End of inner exception stack trace ---
[04:43:40.943] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
[04:43:40.944] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
[04:43:40.945] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
[04:43:40.946] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
[04:43:40.947] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
[04:43:40.949] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
[04:43:40.949] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
[04:43:40.950] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
[04:43:40.950] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
[04:43:40.951] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Core.CorePlugin.AsmResolverDummyDllOutputFormat.DoOutput(ApplicationAnalysisContext context, String outputRoot) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AsmResolverDummyDllOutputFormat.cs:line 88
[04:43:40.952] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 436
[04:43:40.952] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 359

[04:43:49.174] Loading Mods from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Mods'...
[04:43:49.175] 0 Mods loaded.

[04:43:49.187] [ERROR] No Support Module Loaded!

**Comment by wimseden** [comment]
Similar issue, MelonLoader is working but 0 mods loaded.
