### ISSUE TITLE
Failed to apply patches error

### ISSUE THREAD

**Issue by JevilFromVSauce1** [doombubbles/ultimate-crosspathing#93]
# Installation Error

### Mod Version

v1.3.5

### Mod Helper Version

v3.1.3

### Description

For some reason the ultimate crosspath mod is not loading. All the other mods are loading in fine, but this mod is not. I get a red exclamation symbol that when clicked on displays: 
![image](https://user-images.githubusercontent.com/96678782/217650866-6c8061b5-b149-474d-b3f0-29a61f51d3fe.png)
Any help would be appreciated, cheers!

### Other Mods

![image](https://user-images.githubusercontent.com/96678782/217650699-b5b919b4-267e-4e62-b99e-608660c7d1d0.png)

### Logs

[Ultimate_Crosspathing] Unhandled exception in coroutine. It will not continue executing.
System.TypeLoadException: Could not load type 'Assets.Scripts.Unity.UI_New.Popups.PopupScreen' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at UltimateCrosspathing.UltimateCrosspathingMod.<>c.<OnMainMenu>b__0_2()
   at BTD_Mod_Helper.Api.TaskScheduler.Coroutine(Action action, ScheduleType scheduleType, Int32 amountToWait, Func`1 waitCondition)+MoveNext()
   at MelonLoader.Support.MonoEnumeratorWrapper.MoveNext() in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\Il2Cpp\MonoEnumeratorWrapper.cs:line 51

**Longer screenshot of complete log:**
![image](https://user-images.githubusercontent.com/96678782/217651158-312391dd-e69a-465f-9eab-742e3084e449.png)

**Comment by doombubbles** [comment]
Presumably you fixed this already by downloading the latest versions of the mod and mod helper, but yeah this is what will often happen after a new release
