### ISSUE TITLE
Some monkeys fail to load on 35.0

### ISSUE THREAD

**Issue by cyber-wojtek** [doombubbles/ultimate-crosspathing#97]
"[09:58:43.094] [BloonsTD6_Mod_Helper] SuperMonkeyLoader failed loading bytes
[09:58:43.096] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Void Il2CppAssets.Scripts.Models.Towers.Weapons.Behaviors.CritMultiplierModel.set_display(Il2CppAssets.Scripts.Utils.PrefabReference)'.
   at UltimateCrosspathing.Loaders.SuperMonkeyLoader.Set_v_CritMultiplierModel_Fields(Int32 start, Int32 count)
   at UltimateCrosspathing.Loaders.SuperMonkeyLoader.Load(Byte[] bytes) in C:\Users\jpgale\Documents\BTD6 Mods\UltimateCrosspathing\Loaders\SuperMonkeyLoader.cs:line 1777
   at BTD_Mod_Helper.Api.ModByteLoader`1.OnBytesLoaded()
   at BTD_Mod_Helper.Api.ModByteLoader.LoadAllBytes()"

"[09:58:45.662] [Ultimate_Crosspathing] System.NullReferenceException: Object reference not set to an instance of an object.
   at UltimateCrosspathing.Tasks.Loading.Coroutine()+MoveNext() in C:\Users\jpgale\Documents\BTD6 Mods\UltimateCrosspathing\Tasks\LoadTask.cs:line 29
[09:58:45.662] [Ultimate_Crosspathing] Failed loading DartMonkeys :(
[09:58:45.668] [Ultimate_Crosspathing] System.NullReferenceException: Object reference not set to an instance of an object.
   at UltimateCrosspathing.Tasks.Loading.Coroutine()+MoveNext() in C:\Users\jpgale\Documents\BTD6 Mods\UltimateCrosspathing\Tasks\LoadTask.cs:line 29
[09:58:45.668] [Ultimate_Crosspathing] Failed loading SuperMonkeys :("

**Comment by Wardifger** [comment]
Thank you for the dart monkey and super monkey fix! <33
